# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_next_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
