# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='voice_text',
            field=models.CharField(default='Vielen Dank!', max_length=500),
        ),
    ]
